main/urls.py
from django.urls import path, include
from . import views


app_name= 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('registro/', views.registro, name="registro"),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.login_request, name="login"),
    path('guardarCurso/', views.curso_form, name='guardarCurso'),
    path('inscritos_curso/<int:id>/', views.inscritosCurso, name="inscritos_curso"),
  
    path('editarCurso/<int:id>/', views.editarCurso, name= 'editarCurso'),
    path('eliminarCurso/<int:id>/', views.eliminarCurso, name= 'eliminarCurso'),
    path('lista_form/', views.lista_form, name= 'lista_form'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('main.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('inscripcion/', include(('inscripciones.urls', 'inscripciones'), namespace='inscripcion')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime
from django.db.models.fields import BLANK_CHOICE_DASH

# Create your models here.

class Curso(models.Model):
    curso_titulo = models.CharField(max_length= 200)
    curso_contenido = models.TextField()
    curso_publicado = models.DateTimeField(
        "Fecha de publicación", default= datetime.now())
    curso_costo = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.curso_titulo

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.contrib import messages
from inscripciones.models import*
from .models import Curso
from .form import CursoForm
from django.db.models import Sum
#from .form import*
#from django.http import HttpResponseRedirect

# Create your views here.

def homepage(request):
     return render(request, "main/inicio.html", {"cursos": Curso.objects.all})

def registro(request):
     
     if request.method =="POST":
          form = UserCreationForm(request.POST)
          if form.is_valid():
               usuario = form.save()
               nombre_usuario = form.cleaned_data.get('username')
               messages.success(request, f"Nueva Cuenta Creada: {nombre_usuario}")
               login(request, usuario)
               messages.info(request, f"Has sido logeado como: {nombre_usuario}")
               return redirect("main:homepage")
          else:
               for msg in form.error_messages:
                    messages.error(request, f"{msg}: {form.error_messages[msg]}")

     form = UserCreationForm
     return render(request, "main/registro.html", {"form": form})

def logout_request(request):
     logout(request)
     messages.info(request, "Saliste exitosamente")
     return redirect("main:homepage")

def login_request(request):

     if request.method == "POST":
          form = AuthenticationForm(request, data=request.POST)
          if form.is_valid():
               usuario = form.cleaned_data.get('username')
               contraseña = form.cleaned_data.get('password')
               user = authenticate(username=usuario, password= contraseña)
               
               if user is not None:
                    login(request, user)
                    messages.info(request, f"Estás logiado como {usuario}")
                    return redirect("main:homepage")
               else:
                    messages.error(request, "Usuario o contraseña equivocada")
          else:    
               messages.error(request, "Usuario o contraseña equivocada")

     form = AuthenticationForm()
     return render(request, "main/login.html", {"form": form})

def curso_form(request):
    if request.method == 'GET':
        form = CursoForm
        contexto = {
        'form' : form
        }
    else:
        form = CursoForm(request.POST, request.FILES)
        contexto = {
        'form' : form
        }
        if form.is_valid():
               form.save()
               return redirect('main:homepage')

    return render(request,  "main/guardarCurso.html", contexto)


def inscritosCurso(request, id):
    curso = Curso.objects.get(id=id)
    inscritos_curso = Inscripcion.objects.filter(curso = curso)
    suma_costos = inscritos_curso.aggregate(Sum('costo_total'))
    contexto = {
        'curso': curso,
        'inscritos_curso': inscritos_curso, 
        'suma_costos': suma_costos  
    }
    return render(request, 'inscripciones/lista_inscritos.html', contexto)

def lista_form(request):
    return render(request, "main/lista_Cursos.html", {"cursos":Curso.objects.all})


def editarCurso(request,id):
    curso = Curso.objects.get(id = id)
    if request.method == 'GET':
        form = CursoForm(instance= curso)
        contexto = {
            'form': form
        }
    else:
        form = CursoForm(request.POST, request.FILES, instance= curso)
        contexto = {
            'form' : form
        }
        if form.is_valid():
            form.save()
            return redirect('main:lista_form')
    return render(request, "main/guardarCurso.html", contexto)

def eliminarCurso(request,id):
    curso = Curso.objects.get(id = id)
    curso.delete()
    return redirect('main:lista_form')

main/templates/main/guardarCurso.html
{% extends "main/principal.html" %} 

Inscripcion de Estudiantes

{% block content %}

<center><h2>Registrar un nuevo Curso</h2></center>

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}

<center><button type="submit">Crear</button></center>

</form>

{% endblock %}

main/templates/main/inicio.html
{% extends "main/principal.html" %} {% block content %}






{% for cur in cursos %}

<center>
      <div class="row">
      <div class="col s12 m6">
        <div class="card teal darken-3">
          <div class="card-content white-text ">
          <div>
          <p><img src={{cur.image.url}} width="130" height="100"
            style="border: 2px outset; color: orange;" /></p>
          </div
              
          <span class="card-title">{{cur.curso_titulo}}</span>
            <p>{{cur.curso_publicado}}</p>
            <p>{{cur.curso_contenido}}</p>
            <p>{{cur.curso_costo|safe}}</p> 
          </div>
          <div class="card-action">
            <a href="{% url 'inscripciones:inscripcionesform' cur.pk %}">Inscribirse</a>
            <a href="{% url 'main:inscritos_curso' cur.pk %}">Lista de inscritos</a>
            

          </div>
        </div>
      </div>
    {%  endfor  %}
  </div>
  </center>

{% endblock %}

main/templates/main/lista_Cursos.html
{% extends "main/principal.html" %} 
{% block content %}

<center><h1>Lista de Cursos</h1></center>

<form method="POST" enctype="multipart/form-data">
<table class="striped">
    <thead>
        
        <tr>    
            <th>Título</th>    
            <th>Contenido</th>    
            <th>Fecha</th>    
            <th>Precio</th> 
            <th>Imagen</th>
            <th>Opciones</th>    
        </tr>
        
    </thead>

    <tbody>
        {% for cur in cursos %}


        <tr>    
            <td>{{cur.curso_titulo}}</td>    
            <td>{{cur.curso_contenido}}</td>    
            <td>{{cur.curso_publicado}}</td>    
            <td>{{cur.costo}}</td>
            <td><img src={{cur.image.url}} width="130" height="100"  style="border: 2px outset; color: orange;"/></td>
            <td><a href="{% url 'main:editarCurso' cur.id %}">Editar</a>    <a href="{% url 'main:eliminarCurso' cur.id %}">Eliminar</a></td>

        </tr>
        {% endfor %}

    </tbody>

</table>
</form>

{% endblock  %}

main/templates/main/login.html
{% extends "main/principal.html" %} {% block content %}

<form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <button class="btn" type="sumit">Entrar</button>

</form>

Si aún no tienes una cuenta, ve a <a href="/registro">Registro</a>

{% endblock %}

main/templates/main/principal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

    
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'tinymce/css/prism.css' %} ">
    
    <!-- Compiled and minified CSS -->
    <link 
    rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    <title> Cursos</title>

    {% include "main/includes/navbar.html" %}

</head>
<body>


<div class="container">
  <br><br>
  {% block content %} {% endblock %}
</div>


  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
  {% include "main/includes/mensajes.html" %}
    
  <script src="{% static 'tinymce/js/prism.js' %}"></script>
</body>
</html>

main/templates/main/registro.html
{% extends "main/principal.html" %} {% block content %}

<form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <button class="btn" type="sumit">Registrar</button>

</form>

Si ya tienes una cuenta, ve a <a href="/login">Entrar</a>

{% endblock %}