inscripciones/urls.py
from django.urls import path, include
from . import views



urlpatterns = [
        path('inscripcionesform/<int:pk>/', views.inscripcionesform, name='inscripcionesform'),
        path('lista_estudiantes/', views.lista_estudiantes, name='lista_estudiantes'),
        path('eliminar_inscripcion/<int:id>/', views.eliminar_inscripcion, name= 'eliminar_inscripcion'),
        path('editar_inscripcion/<int:id>/', views.editar_inscripcion, name= 'editar_inscripcion'),
]

main/urls.py
from django.urls import path, include
from . import views


app_name= 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('registro/', views.registro, name="registro"),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.login_request, name="login"),
    path('guardarCurso/', views.curso_form, name='guardarCurso'),
    path('inscritos_curso/<int:id>/', views.inscritosCurso, name="inscritos_curso"),
  
    path('editarCurso/<int:id>/', views.editarCurso, name= 'editarCurso'),
    path('eliminarCurso/<int:id>/', views.eliminarCurso, name= 'eliminarCurso'),
    path('lista_form/', views.lista_form, name= 'lista_form'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('main.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('inscripcion/', include(('inscripciones.urls', 'inscripciones'), namespace='inscripcion')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime
from django.db.models.fields import BLANK_CHOICE_DASH

# Create your models here.

class Curso(models.Model):
    curso_titulo = models.CharField(max_length= 200)
    curso_contenido = models.TextField()
    curso_publicado = models.DateTimeField(
        "Fecha de publicación", default= datetime.now())
    curso_costo = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.curso_titulo

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.contrib import messages
from inscripciones.models import*
from .models import Curso
from .form import CursoForm
from django.db.models import Sum
#from .form import*
#from django.http import HttpResponseRedirect

# Create your views here.

def homepage(request):
     return render(request, "main/inicio.html", {"cursos": Curso.objects.all})

def registro(request):
     
     if request.method =="POST":
          form = UserCreationForm(request.POST)
          if form.is_valid():
               usuario = form.save()
               nombre_usuario = form.cleaned_data.get('username')
               messages.success(request, f"Nueva Cuenta Creada: {nombre_usuario}")
               login(request, usuario)
               messages.info(request, f"Has sido logeado como: {nombre_usuario}")
               return redirect("main:homepage")
          else:
               for msg in form.error_messages:
                    messages.error(request, f"{msg}: {form.error_messages[msg]}")

     form = UserCreationForm
     return render(request, "main/registro.html", {"form": form})

def logout_request(request):
     logout(request)
     messages.info(request, "Saliste exitosamente")
     return redirect("main:homepage")

def login_request(request):

     if request.method == "POST":
          form = AuthenticationForm(request, data=request.POST)
          if form.is_valid():
               usuario = form.cleaned_data.get('username')
               contraseña = form.cleaned_data.get('password')
               user = authenticate(username=usuario, password= contraseña)
               
               if user is not None:
                    login(request, user)
                    messages.info(request, f"Estás logiado como {usuario}")
                    return redirect("main:homepage")
               else:
                    messages.error(request, "Usuario o contraseña equivocada")
          else:    
               messages.error(request, "Usuario o contraseña equivocada")

     form = AuthenticationForm()
     return render(request, "main/login.html", {"form": form})

def curso_form(request):
    if request.method == 'GET':
        form = CursoForm
        contexto = {
        'form' : form
        }
    else:
        form = CursoForm(request.POST, request.FILES)
        contexto = {
        'form' : form
        }
        if form.is_valid():
               form.save()
               return redirect('main:homepage')

    return render(request,  "main/guardarCurso.html", contexto)


def inscritosCurso(request, id):
    curso = Curso.objects.get(id=id)
    inscritos_curso = Inscripcion.objects.filter(curso = curso)
    suma_costos = inscritos_curso.aggregate(Sum('costo_total'))
    contexto = {
        'curso': curso,
        'inscritos_curso': inscritos_curso, 
        'suma_costos': suma_costos  
    }
    return render(request, 'inscripciones/lista_inscritos.html', contexto)

def lista_form(request):
    return render(request, "main/lista_Cursos.html", {"cursos":Curso.objects.all})


def editarCurso(request,id):
    curso = Curso.objects.get(id = id)
    if request.method == 'GET':
        form = CursoForm(instance= curso)
        contexto = {
            'form': form
        }
    else:
        form = CursoForm(request.POST, request.FILES, instance= curso)
        contexto = {
            'form' : form
        }
        if form.is_valid():
            form.save()
            return redirect('main:lista_form')
    return render(request, "main/guardarCurso.html", contexto)

def eliminarCurso(request,id):
    curso = Curso.objects.get(id = id)
    curso.delete()
    return redirect('main:lista_form')

main/templates/main/includes/mensajes.html
{% if messages %}
    {% for message in messages %}

      <!--exito-->
      {% if message.tags == 'success' %}       
        <script>
          M.toast({
            html: '{{message}}',
            classes:'green rounded',
            displayLength: 4000,
          });
        </script>
      {%  endif  %}

      <!--info-->
      {% if message.tags == 'info' %}       
        <script>
          M.toast({
            html: '{{message}}',
            classes:'blue rounded',
            displayLength: 4000,
          });
        </script>
      {%  endif  %}

      <!--warning-->
      {% if message.tags == 'warning' %}       
        <script>
          M.toast({
            html: '{{message}}',
            classes:'orange rounded',
            displayLength: 4000,
          });
        </script>
      {%  endif  %}

      <!--error-->
      {% if message.tags == 'error' %}       
        <script>
          M.toast({
            html: '{{message}}',
            classes:'red rounded',
            displayLength: 5000,
          });
        </script>
      {%  endif  %}

    {%  endfor  %}
  {%  endif  %}   

main/templates/main/includes/navbar.html
<nav>
    <div class="nav-wrapper  orange darken-2" >
      <a href="/" class="brand-logo">Cursos</a>
      <ul id="nav-mobile" class="right e65100 orange darken-4">
        <li><a href="/">Inicio  |</a></li>

        {% if user.is_authenticated %}
          <li></a>{{user.username}} </a></li>
          <li><a href="/guardarCurso">Agregar Curso  |</a></li>
          <li><a href="{% url 'inscripcion:lista_estudiantes' %}">Lista de Estudiantes  |</a></li>
          <li><a href="{% url 'main:lista_form' %}">Lista de Cursos  |</a></li>
          <li><a href="/logout">Salir</a></li>
        {% else %}
          <li><a href="{% url 'main:registro' %}">registro  |</a></li>
          <li><a href="/login">Entrar  |</a></li>
          
        {% endif %} 

      </ul>
    </div>
  </nav>